export const surveyTheme = {
  cssVariables: {
    '--sjs-general-backcolor': '#ffffff',
    '--sjs-general-backcolor-dark': '#f8f8f8',
    '--sjs-general-backcolor-dim': '#F3F3F3',
    '--sjs-general-backcolor-dim-light': '#f9f9f9',
    '--sjs-general-backcolor-dim-dark': '#f3f3f3',
    '--sjs-general-forecolor': '#000000e8',
    '--sjs-general-forecolor-light': '#00000073',
    '--sjs-general-dim-forecolor': '#000000e8',
    '--sjs-general-dim-forecolor-light': '#00000073',
    '--sjs-primary-backcolor': '#19b394',
    '--sjs-primary-backcolor-light': '#19b3941a',
    '--sjs-primary-backcolor-dark': '#14a48b',
    '--sjs-primary-forecolor': '#ffffff',
    '--sjs-primary-forecolor-light': '#ffffff40',
    '--sjs-base-unit': '8px',
    '--sjs-corner-radius': '4px',
    '--sjs-secondary-backcolor': '#ff9814',
    '--sjs-secondary-backcolor-light': '#ff98141a',
    '--sjs-secondary-backcolor-semi-light': '#ff981440',
    '--sjs-secondary-forecolor': '#ffffff',
    '--sjs-secondary-forecolor-light': '#ffffff40',
    '--sjs-shadow-small': '0px 1px 2px 0px #00000026',
    '--sjs-shadow-medium': '0px 2px 6px 0px #0000001a',
    '--sjs-shadow-large': '0px 8px 16px 0px #0000001a',
    '--sjs-shadow-inner': 'inset 0px 1px 2px 0px #00000026',
    '--sjs-border-light': '#00000017',
    '--sjs-border-default': '#00000029',
    '--sjs-border-inside': '#00000029',
    '--sjs-special-red': '#e50a3e',
    '--sjs-special-red-light': '#e50a3e1a',
    '--sjs-special-green': '#19b394',
    '--sjs-special-green-light': '#19b3941a',
    '--sjs-special-blue': '#437fd9',
    '--sjs-special-blue-light': '#437fd91a',
    '--sjs-special-yellow': '#ff9814',
    '--sjs-special-yellow-light': '#ff98141a',
    '--sjs-article-font-xx-large-fontSize': '64px',
    '--sjs-article-font-xx-large-textDecoration': 'none',
    '--sjs-article-font-xx-large-fontWeight': '700',
    '--sjs-article-font-xx-large-fontStyle': 'normal',
    '--sjs-article-font-xx-large-fontStretch': 'normal',
    '--sjs-article-font-xx-large-letterSpacing': '0',
    '--sjs-article-font-xx-large-lineHeight': '64px',
    '--sjs-article-font-xx-large-paragraphIndent': '0px',
    '--sjs-article-font-xx-large-textCase': 'none',
    '--sjs-article-font-x-large-fontSize': '48px',
    '--sjs-article-font-x-large-textDecoration': 'none',
    '--sjs-article-font-x-large-fontWeight': '700',
    '--sjs-article-font-x-large-fontStyle': 'normal',
    '--sjs-article-font-x-large-fontStretch': 'normal',
    '--sjs-article-font-x-large-letterSpacing': '0',
    '--sjs-article-font-x-large-lineHeight': '56px',
    '--sjs-article-font-x-large-paragraphIndent': '0px',
    '--sjs-article-font-x-large-textCase': 'none',
    '--sjs-article-font-large-fontSize': '32px',
    '--sjs-article-font-large-textDecoration': 'none',
    '--sjs-article-font-large-fontWeight': '700',
    '--sjs-article-font-large-fontStyle': 'normal',
    '--sjs-article-font-large-fontStretch': 'normal',
    '--sjs-article-font-large-letterSpacing': '0',
    '--sjs-article-font-large-lineHeight': '40px',
    '--sjs-article-font-large-paragraphIndent': '0px',
    '--sjs-article-font-large-textCase': 'none',
    '--sjs-article-font-medium-fontSize': '24px',
    '--sjs-article-font-medium-textDecoration': 'none',
    '--sjs-article-font-medium-fontWeight': '700',
    '--sjs-article-font-medium-fontStyle': 'normal',
    '--sjs-article-font-medium-fontStretch': 'normal',
    '--sjs-article-font-medium-letterSpacing': '0',
    '--sjs-article-font-medium-lineHeight': '32px',
    '--sjs-article-font-medium-paragraphIndent': '0px',
    '--sjs-article-font-medium-textCase': 'none',
    '--sjs-article-font-default-fontSize': '16px',
    '--sjs-article-font-default-textDecoration': 'none',
    '--sjs-article-font-default-fontWeight': '400',
    '--sjs-article-font-default-fontStyle': 'normal',
    '--sjs-article-font-default-fontStretch': 'normal',
    '--sjs-article-font-default-letterSpacing': '0',
    '--sjs-article-font-default-lineHeight': '28px',
    '--sjs-article-font-default-paragraphIndent': '0px',
    '--sjs-article-font-default-textCase': 'none',
  },
  isCompact: false,
  themeName: 'custom',
  colorPalette: 'light',
  header: {
    height: '256px',
    inheritWidthFrom: 'container',
    textAreaWidth: '512px',
    overlapEnabled: true,
    backgroundImage:
      'https://api.surveyjs.io/private/Surveys/files?name=2000a1d1-9649-4994-a794-381343837eaa',
    backgroundImageOpacity: 1,
    backgroundImageFit: 'cover',
    logoPositionX: 'right',
    logoPositionY: 'top',
    titlePositionX: 'left',
    titlePositionY: 'bottom',
    descriptionPositionX: 'left',
    descriptionPositionY: 'bottom',
  },
  headerView: 'advanced',
};
